### PR TITLE
changed to pull latest 4 months of events

### PR DESCRIPTION
**Pull request by AllanT102**
🎟️ **Ticket(s):**
Closes #

👷 **Changes:**
Changed events getAll to query latest four months of events instead of all to speed up query.

💭 **Notes:**
Any additional things to take into consideration.

**Wait! Before you merge, have you checked the following:**
- [ ] Serverless tests are passing (Check travis build logs, CI is currently broken)
- [ ] PR is has approving review(s)

### CODE REVIEW

**Comment by voctory** [comment]
Hey @AllanT102, I don't think this change has any effect on the RCUs we consume from DynamoDB because the filters are applied after every event is fetched - I'd expect latency to be mostly unchanged unless your testing suggested differently?

From https://dynobase.dev/dynamodb-scan/
> FilterExpressions do not affect the actual act of reading from the database! Filters are applied after the data is read from the database and before returning it to the user. This means that the load on the database and the cost of executing the query is still the same (because we're billed on the "scanned space"), the only thing that changes is the result returned to the client and the size of the payload sent between you and AWS Cloud.

**Comment by AllanT102** [comment]
> Hey @AllanT102, I don't think this change has any effect on the RCUs we consume from DynamoDB because the filters are applied after every event is fetched - I'd expect latency to be mostly unchanged unless your testing suggested differently?
> 
> From https://dynobase.dev/dynamodb-scan/
> 
> > FilterExpressions do not affect the actual act of reading from the database! Filters are applied after the data is read from the database and before returning it to the user. This means that the load on the database and the cost of executing the query is still the same (because we're billed on the "scanned space"), the only thing that changes is the result returned to the client and the size of the payload sent between you and AWS Cloud.

Good note @voctory should probably use query instead if we can. Unless you've already upgraded the RCU capacity, it seems to be working rn tho? events page is still loading which means it's not being throttled like it was before. it does seem like the latency has improved – although I haven't tested it with numbers yet, could just feel faster bc dev doesn't have many events the fetch in the first place haha

**Comment by voctory** [comment]
@AllanT102 Yes the dev Events table had its RCU limit removed over the weekend

**Comment by voctory** [comment]
I could set it back to the previous limit if we want to compare the throttling? Lmk

**Comment by AllanT102** [comment]
Oh yeah let's do that

**Comment by voctory** [comment]
Previous limit has been brought back

**Pull request merged**
